name: thing_toast
description: "Package for Fancy Gradient Toast."
version: 0.1.0
repository: https://github.com/codestrdy/thing_toast

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  iconsax_plus: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
